export const BANNED = [
  "% of your life",
  "productivity score",
  "time you focused",
  "you didn't use",
  "addiction",
  "ADHD",
  "cure",
  "detox",
  "wellbeing diagnosis",
] as const;

export const COPY = {
  eggLine1: "Nothing is tracked yet.",
  eggLine2: "The first honest day starts tomorrow.",
  webHonestyHeadline: "How the numbers are made",
  webHonestyBody:
    "Timeframe replays what the writers recorded — the app on the phone, and your browser once you import its export. It never asks you to start a timer, and it never guesses what it didn't measure.",
  webHonestyDisclosure: "The phone app is the writer. This page is the mirror.",
  savePins: "Save pins",
  bannerPhone: (day: string) => `Phone tracker off since ${day}`,
  bannerComputer: (day: string) => `Computer tracker off since ${day}`,
  turnOn: "Turn on",
  reEnable: "Re-enable",
  lightDay: "light day — not comparable",
  unclassifiedBadge: (n: number) => `${n}% unclassified`,
  pinYourApps: "Pin your apps",
  reviewUnclassified: "Review unclassified",
  pinChess: "Pin chess to work or killers.",
  pinSub: "Pre-checked defaults — edit any time in the first week",
  deepZero: (n: number) => `0 blocks ≥15 min · longest ${n} min`,
  labelFocus: "Focus-set time",
  labelSink: "Sink",
  labelBlocks: "Blocks ≥15 min",
  labelLongest: "longest",
  sinkEmpty: "No killer-set time tracked",
  cardEmpty: "No tracked time yet",
  mixHeader: "Share of tracked time",
  mixCaption: "% of tracked time",
  heatmapHeader: "When tracked time happened",
  broken: (killer: string, n: number) => `Broken — ${killer} was open ${n}s`,
  brokenPrivate: "Broken — private app",
  startBlock: "Start block",
  endBlock: "End block",
  newBlock: "New block",
  cancelled: "Cancelled",
  completed: "Completed",
  targetReached: (n: number) => `target reached · ${n} min`,
  focusLive: "focus-set time · live",
  endOfReplay: "End of replay",
  replayLabel: "Replay — this page walks a recorded day. It is not live sampling.",
  deathFloor: "Death floor — when a killer ends a block",
  demoPill: "Demo data — these numbers are from a sample week.",
  weekEmpty: "No tracked time in this range",
  weekEmptySub: "The card never renders without a label and data.",
  preflight: "Private apps stay off this card.",
  footerTemplate:
    "Tracked {D} days · phone up {D_p}/{D} · computer up {D_c}/{D} · unclassified {U}% · double-counted {H}h",
  heroThesis: "The phone and the browser already know. Timeframe just tells you the truth.",
  ctaLedger: "See the honest ledger",
  ctaPro: "Start Pro",
  footnote: "Honest approximations of screen occupancy — never attention, never intent.",
  pricingHeadline: "The ledger is free forever. You pay for the creature and the card.",
  freeSub:
    'No card. The three daily numbers, the heatmap, the "tracker off" banner — free, for good.',
  paidSub:
    "Everything in Free, plus: a creature that grows with your focus-set time, streaks, the killer that broke the block by name, and the clean share card.",
  paidHeader: "Pro — ₹499/month · ₹2,999/year · or ₹599 once (classic skin, forever)",
  gstLine: "All prices in ₹ (INR), inclusive of 18% GST.",
  paymentOffline: "Payment needs a connection",
  ledgerUnreadable: "The ledger couldn't be read",
  ledgerUnreadableSub: "Nothing was fabricated. Try reading it again.",
  tryAgain: "Try again",
  numberFailed: "This number couldn't be computed",
  badExport: "That file isn't a Timeframe export",
  importTooLarge: "Import too large — export and re-import a shorter range.",
  importResult: (n: number) => `${n} sessions imported · no duplicates`,
  exportResult: (n: number) => `Exported ${n} sessions`,
  terms:
    "Timeframe stub terms. Timeframe logs which app or site is in the foreground so you can see your own focus-set time and sink time. The ledger stays on your device by default. The ledger is free forever; paid unlocks the creature and the clean share card. Refunds: 7 days, full, no questions asked (see payment page). Full terms replace this stub before live launch.",
  privacy:
    "Timeframe stub privacy. We collect your usage times (apps and domains, durations) to show you your own ledger — % of tracked time — on your device. Local-first: the ledger never leaves your device by default. No ads, no trackers, no sale or sharing of your data. Deleting the app or extension deletes the data. Full privacy policy replaces this stub before live launch.",
  unitFocus: "h focus-set time",
  unitSink: "h sink time",
  unitBlocks: "blocks ≥15 min",
  sourcePhone: "phone",
  sourceComputer: "computer",
  lastWrite: (phone: string, computer: string) =>
    `last write: phone ${phone} · computer ${computer}`,
  navDashboard: "Dashboard",
  navWeek: "Week",
  navBlock: "Block",
  navDebrief: "Debrief",
  navSite: "Timeframe",
  phoneThisWeek: "phone this week",
  laptopThisWeek: "laptop this week",
  mergedExport: "merged export",
  noData: "no data",
  zeroMin: "0 min",
  habitatIdle: "no blocks yet",
  habitatStreak: (n: number) => `${n} day streak · no blocks yet`,
  skipHonesty: "Continue",
} as const;

export function formatFooter(args: {
  D: number;
  Dp: number;
  Dc: number;
  U: number;
  H: number;
}): string {
  const H = args.H.toFixed(2);
  return `Tracked ${args.D} days · phone up ${args.Dp}/${args.D} · computer up ${args.Dc}/${args.D} · unclassified ${args.U}% · double-counted ${H}h`;
}

export function scanBanned(text: string): string[] {
  const lower = text.toLowerCase();
  return BANNED.filter((p) => lower.includes(p.toLowerCase()));
}

export const ALL_SHIPPED_STRINGS: string[] = [
  COPY.eggLine1,
  COPY.eggLine2,
  COPY.webHonestyHeadline,
  COPY.webHonestyBody,
  COPY.webHonestyDisclosure,
  COPY.savePins,
  COPY.turnOn,
  COPY.reEnable,
  COPY.lightDay,
  COPY.pinYourApps,
  COPY.reviewUnclassified,
  COPY.pinChess,
  COPY.pinSub,
  COPY.labelFocus,
  COPY.labelSink,
  COPY.labelBlocks,
  COPY.labelLongest,
  COPY.sinkEmpty,
  COPY.cardEmpty,
  COPY.mixHeader,
  COPY.mixCaption,
  COPY.heatmapHeader,
  COPY.startBlock,
  COPY.endBlock,
  COPY.newBlock,
  COPY.cancelled,
  COPY.completed,
  COPY.focusLive,
  COPY.endOfReplay,
  COPY.replayLabel,
  COPY.deathFloor,
  COPY.demoPill,
  COPY.weekEmpty,
  COPY.weekEmptySub,
  COPY.preflight,
  COPY.heroThesis,
  COPY.ctaLedger,
  COPY.ctaPro,
  COPY.footnote,
  COPY.pricingHeadline,
  COPY.freeSub,
  COPY.paidSub,
  COPY.paidHeader,
  COPY.gstLine,
  COPY.paymentOffline,
  COPY.ledgerUnreadable,
  COPY.ledgerUnreadableSub,
  COPY.tryAgain,
  COPY.numberFailed,
  COPY.badExport,
  COPY.importTooLarge,
  COPY.terms,
  COPY.privacy,
  COPY.unitFocus,
  COPY.unitSink,
  COPY.unitBlocks,
  COPY.habitatIdle,
];
