/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as BlockRouteImport } from './routes/block'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DebriefRouteImport } from './routes/debrief'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WeekRouteImport } from './routes/week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockRoute = BlockRouteImport.update({
  id: '/block',
  path: '/block',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DebriefRoute = DebriefRouteImport.update({
  id: '/debrief',
  path: '/debrief',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekRoute = WeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/block': typeof BlockRoute
  '/checkout': typeof CheckoutRoute
  '/debrief': typeof DebriefRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/week': typeof WeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/block': typeof BlockRoute
  '/checkout': typeof CheckoutRoute
  '/debrief': typeof DebriefRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/week': typeof WeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/block': typeof BlockRoute
  '/checkout': typeof CheckoutRoute
  '/debrief': typeof DebriefRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/week': typeof WeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/block'
    | '/checkout'
    | '/debrief'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/block'
    | '/checkout'
    | '/debrief'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/week'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/block'
    | '/checkout'
    | '/debrief'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BlockRoute: typeof BlockRoute
  CheckoutRoute: typeof CheckoutRoute
  DebriefRoute: typeof DebriefRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WeekRoute: typeof WeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/block': {
      id: '/block'
      path: '/block'
      fullPath: '/block'
      preLoaderRoute: typeof BlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debrief': {
      id: '/debrief'
      path: '/debrief'
      fullPath: '/debrief'
      preLoaderRoute: typeof DebriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week': {
      id: '/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof WeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BlockRoute: BlockRoute,
  CheckoutRoute: CheckoutRoute,
  DebriefRoute: DebriefRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WeekRoute: WeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
